kind: Deployment
apiVersion: apps/v1
metadata:
    name: node-pong
spec:
    replicas: 1
    selector:
        matchLabels:
            app: node-pong
    template:
        metadata:
            labels:
                app: node-pong
        spec:
            containers:
                - name: node-pong
                  image: maeganwomble/node-pong
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3001
            restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
    name: node-pong
spec:
    type: NodePort
    ports:
        - port: 3001
          targetPort: 3001
          protocol: TCP
          nodePort: 30001
    selector:
        app: node-pong
