kind: Deployment
apiVersion: apps/v1
metadata:
    name: react-pong
spec:
    replicas: 1
    selector:
        matchLabels:
            app: react-pong
    template:
        metadata:
            labels:
                app: react-pong
        spec:
            containers:
                - name: react-pong
                  image: maeganwomble/react-pong
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
            restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
    name: react-pong
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          nodePort: 31000
    selector:
        app: react-pong
